### ISSUE TITLE
scrollbar too light

### ISSUE THREAD

**Issue by kuchengrab** [halloichbingunnar/weimar-css#3]
henlo

ich finde die scrollbar (bzw. das dings, das anzeigt, wo man ist und das man anfassen kann, wie heißt den?) zu schwer erkennbar, zumal es ja auf grauem hintergrund flutscht:
![image](https://user-images.githubusercontent.com/46924279/118507732-cbc50f00-b72e-11eb-9c2d-134a5756cbea.png)

vielleicht reicht es schon, es eine graustufe dunkler zu machen. hab das ding leider nicht gefunden mit dem inspector.

lg inspector claus
institut für angewandte prokrastination

**Comment by halloichbingunnar** [comment]
issue macht sinn, wobei ich das eigentlich gern so unauffällig wie möglich hätte, weil man weiß ja eh dass das existiert und findet es, wenn man danach sucht...

```css
    body ::-webkit-scrollbar-thumb {
        background-color: var(--grey-1) !important;
    }
```
wenn grey-2 ist es schon fast wieder zu dominant 🤷🏻‍♂️
